---
title: "Introducción"
---

# Bibliografía {.unnumbered .unlisted}

**Stiglitz** y **Rosengard** (2016): *La economía del sector público*.

-   Capítulo 1: "Definición de las responsabilidades del sector público".

-   Capítulo 2: "La medición  de las dimensiones del sector público".

**Albi**, **González-Páramo**, **Urbanos** y **Zubiri** (2018): *Economía Pública, volumen I*.

-   Capítulo 2: "El Sector Público y el presupuesto".

# Delimitación del sector público

## ¿Qué es el sector público?

¿Qué distingue el sector público del sector privado?

## Intervención pública

-   ¿Qué razones justifican la intervención pública en la economía?

-   ¿Qué actividades desarrolla el sector público?

## Medición de las actividades del sector público

-   Gastos.

-   Ingresos.

-   Déficit y deuda pública.

## Análisis económico del sector público

-   **Análisis positivo** frente a **análisis normativo.**

-   Preguntas básicas:

    -   ¿**Qué** producir?

    -   ¿**Cómo** producir?

    -   ¿**Para quién** producir?

    -   ¿**Cómo se toman las decisiones** dentro del sector público?

# El sector público en España

## Estructura del sector público en España

-   Administraciones públicas.

-   Sector público empresarial.

## Las administraciones públicas

-   Administración Central:

    -   Estado.

    -   Organismos de la Administración Central.

-   Administración Regional.

-   Administración Local.

-   Fondos de la Seguridad Social.

## El sector público empresarial

-   Sociedades no financieras.

-   Instituciones financieras públicas.
