project:
  title: "pres-ec1047"
  output-dir: "html"
  render:
    - "01 - Intro.qmd"

editor: visual
lang: es
subtitle: |
  | EC1047 --- Economía del Sector Público
  | Curso 2024--2025
toc: true
toc-depth: 1
number-sections: true
number-depth: 1


format:
  revealjs:
    embed-resources: true
    theme: "night"
    transition: "none"
    slideNumber: false
    controls: false
    progress: false
    history: true
    center: true
    width: 1920
    height: 1080
    margin: 0.1
    minScale: 0.2
    maxScale: 1.5
